{{- if .Values.useFaultTolerance }}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "name" . }}-{{ .Release.Name }}
  labels:
    app:  {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: {{ .Values.storageClass }}
  resources:
    requests:
      storage: {{ .Values.storageSize }}
{{- end -}}
